### ISSUE TITLE
Compile in production mode

### ISSUE THREAD

**Issue by simonschaufi** [punktDe/neos-environment-display#1]
Run node In production mode for build. See https://github.com/Sebobo/Shel.Neos.Hyphens/blob/40bcf58b0638aaa5a066bd14a30322dae812b2a0/Resources/Private/Scripts/HyphensEditor/package.json#L5

**Comment by c4ll-m3-j4ck** [comment]
Thank you for pointing that out! 
I've updated the build command and released a new version (1.0.0 for easier use with composer update).
